### ISSUE TITLE
BDD testing

### ISSUE THREAD

**Issue by RoyalPetya** [BME-MIT-IET/iet-hf-2023-vilagtalan-varazslok#10]
Cucumber

**Comment by FischerBalazs** [comment]
Teszt 18-21 kész van!

**Comment by LorddTyrion** [comment]
Teszt 34, 35, 37 kész

**Comment by LorddTyrion** [comment]
Megjegyzés, a sorszámok itt a porjlab-os dokumentum részletes terveinek sorszámainak felenek meg, ezek egy részhalmazát valósítjuk meg Cucumberben.

**Comment by RoyalPetya** [comment]
teszt 2-5 kész
